version: '2'

services:
  console:
    build:
      context: ./docker/console
    environment:
      - PHP_IDE_CONFIG=serverName=third_rail_packages_queue_subscriber
    working_dir: /app
    env_file: .env
    volumes:
        - .:/app
  activemq:
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 8161:8161
      - 61313:61613
