<?php

namespace TrainjunkiesPackages\QueueSubscriber\NetworkRail\Topics;

class TrainDescriber
{
    const TD_ALL_AREAS = 'TD_ALL_SIG_AREA';
    const TD_ANGLIA_AREA = 'TD_ANG_SIG_AREA';
    const TD_KENT_MIDLANDS_CONTINENTAL_AREA = 'TD_KENT_MCC_SIG_AREA';
    const TD_LONDON_NE_GREAT_NORTHERN_AREA = 'TD_LNE_GN_SIG_AREA';
    const TD_LONDON_NE_NORTH_EAST_AREA = 'TD_LNE_NE_SIG_AREA';
    const TD_LONDON_NW_CENTRAL_AREA = 'TD_LNW_C_SIG_AREA';
    const TD_LONDON_NW_LANCASHIRE_CUMBRIA_AREA_ = 'TD_LNW_LC_SIG_AREA';
    const TD_LONDON_NW_WEST_MIDLANDS_AREA = 'TD_LNW_WMC_SIG_AREA';
    const TD_MIDLANDS_CONTINENTAL_EAST_MIDLANDS_AREA = 'TD_MC_EM_SIG_AREA';
    const TD_SCOTLAND_EAST_AREA = 'TD_SE_SIG_AREA';
    const TD_SCOTLAND_WEST_AREA = 'TD_SW_SIG_AREA';
    const TD_SUSSEX_AREA = 'TD_SUSS_SIG_AREA';
    const TD_WESSEX_AREA = 'TD_WESS_SIG_AREA';
    const TD_WESTERN_THAMES_VALLEY_AREA = 'TD_WTV_SIG_AREA';
    const TD_WESTERN_WALES_MARCHES = 'TD_WWM_SIG_AREA';
    const TD_WESTERN_WEST_COUNTRY = 'TD_WWC_SIG_AREA';
    const TD_WEST_COAST_SOUTH_AREA = 'TD_WCS_SIG_AREA';
}
